name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    env:
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install && npm install -g @lhci/cli@0.4.x
      - run: npm run build
      - run: lhci autorun

#name: CI
#on: [push]
#jobs:
#  lhci:
#    name: Lighthouse
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js 10.x
#        uses: actions/setup-node@v1
#        with:
#          node-version: 10.x
#      - name: npm install, build
#        run: |
#          npm install
#          npm run build
#      - name: run Lighthouse CI
#        run: |
#          npm install -g @lhci/cli@0.4.x
#          lhci autorun
